# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51c703e44fdea8e772352d737910770f34c85cd67763aec7a4cd41a73f6159499390d5091ad09ef47530db29eb04f18ae75807b46d59dad9e9893e4c4b40935

test:
  secret_key_base: 55b2072e77f8f9d568f2ed401d6a571f0f54aa945b263fdf4117b2bfa9e96da7627f4e2ffe72198af016685c6b30ee59f18bd8b64fd1c16696994bd67bb69763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
